apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: consul-release-controller-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - consul-release-controller.nicholasjackson.io
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - consul-release-controller.nicholasjackson.io
  resources:
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - consul-release-controller.nicholasjackson.io
  resources:
  - releases/status
  verbs:
  - get
  - patch
  - update
