---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul-release-controller.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "consul-release-controller.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: consul-release-controller
  ports:
  - name: http
    protocol: TCP
    port: 9443
    targetPort: 9443
  - name: webhook
    protocol: TCP
    port: 19443
    targetPort: 19443
  - name: metrics
    protocol: TCP
    port: 9102
    targetPort: 9102