apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding
subjects:
- kind: ServiceAccount
  name: '{{ include "consul-release-controller.serviceAccountName" . }}'
  namespace: '{{ default .Release.Namespace }}'